# Generated by Django 5.0.7 on 2024-08-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_alter_lga_user_alter_national_user_alter_state_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='name',
        ),
        migrations.AddField(
            model_name='ward',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='membership_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
