# Generated by Django 5.0.7 on 2024-08-02 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_remove_lga_created_at_remove_lga_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lga',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
