# Generated by Django 5.0.7 on 2024-08-15 23:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0006_pollingunit_ward_pollingunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollingUnitAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent_status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('polling_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_unit_agents', to='Registration.pollingunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.ward')),
            ],
        ),
    ]
