# Generated by Django 5.0.7 on 2024-08-22 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0007_pollingunitagent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='MyState',
        ),
    ]
